version: "3.6"

services:
  db:
    image: postgres:12.9-alpine
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=support
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=14863
    ports:
      - '5432:5432'
    network_mode: "host"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/support
    ports:
      - '8000:8000'
    environment:
        - POSTGRES_NAME=support
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=14863
    depends_on:
      - db
    network_mode: "host"

  redis:
    image: redis:alpine
    network_mode: "host"

  celery:
    restart: always
    build:
      context: .
    command: celery -A support worker -l info
    volumes:
      - .:/usr/src/support
    environment:
      - POSTGRES_NAME=support
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=14863
    depends_on:
      - db
      - redis
      - web
    network_mode: "host"
volumes:
  data:
